service: serverless-nestjs-baby

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-offline
  - serverless-sentry
  - serverless-plugin-warmup

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  environment:
    SENTRY_ENVIRONMENT: ${opt:stage, self:provider.stage}
    SENTRY_FILTER_LOCAL: true
    SENTRY_CAPTURE_ERRORS: true
    SENTRY_CAPTURE_UNHANDLED: true
    SENTRY_CAPTURE_MEMORY: true
    SENTRY_CAPTURE_TIMEOUTS: true

functions:
  main:
    handler: src/lambda.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'

custom:
  warmup:
    default:
      enabled: true
      events:
        - schedule: rate(5 minutes)
      concurrency: 10
  sentry:
    dsn: https://77110066cfeb430ea73fc446c914dcba@o1342385.ingest.sentry.io/6616457 # URL provided by Sentry